"""add user profile fields

Revision ID: 8abb7fbb428a
Revises: 18ca285772d8
Create Date: 2025-10-12 22:05:03.856400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8abb7fbb428a'
down_revision = '18ca285772d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('grade', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('class_name', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('class_name')
        batch_op.drop_column('grade')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
