"""add document fields

Revision ID: add_document_fields
Revises: 8abb7fbb428a
Create Date: 2025-01-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_document_fields'
down_revision = '8abb7fbb428a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 检查现有的列
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('document')]
    
    with op.batch_alter_table('document', schema=None) as batch_op:
        if 'original_name' not in columns:
            batch_op.add_column(sa.Column('original_name', sa.String(length=255), nullable=False, server_default=''))
        if 'file_path' not in columns:
            batch_op.add_column(sa.Column('file_path', sa.String(length=1024), nullable=False, server_default=''))
        if 'file_size' not in columns:
            batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=False, server_default='0'))
        if 'file_type' not in columns:
            batch_op.add_column(sa.Column('file_type', sa.String(length=32), nullable=False, server_default=''))
        if 'url' in columns:
            batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=1024), nullable=True))
        batch_op.drop_column('file_type')
        batch_op.drop_column('file_size')
        batch_op.drop_column('file_path')
        batch_op.drop_column('original_name')

    # ### end Alembic commands ###



